spec_version: 2
description: Simple s3 buckets provisioning

inputs:
  host_name:
    type: agent

outputs:
  bucket_1:
    value: '{{ .grains.bucket_1.outputs.s3_bucket_arn }}'

grains:
  bucket_1:
    kind: terraform
    spec: 
      source:
        path: https://github.com/TomerAdmon/torque-demo.git//terraform/s3
      agent:
        name: '{{ .inputs.agent }}'
      inputs:
        - region: us-west-1
        - acl: private
        - name: 'demo-s3-bucket-1-{{ sandboxid | downcase }}'
      outputs:
        - s3_bucket_arn
